services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
      - ./angular.json:/app/angular.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      -NODE_ENV: development
    command: ng serve --host 0.0.0.0